### ISSUE TITLE
Documentation: Planning Docs

### ISSUE THREAD

**Issue by akachru-github** [nci-hcmi-catalog/roadmap#9]
We re required to complete the following planning documentation by Jan 24 2020: 
- Project Management plan
- UI Changes plan
- Stability plan
- Monitoring plan
- Software Upgrade plan
- Testing plan

This epic can be closed once these are completed.

**Comment by touhidulmridha** [comment]
@akachru-github - I've already revised these documents again this morning, please let me know if anything else needs to be done here. Google Docs Link: https://drive.google.com/drive/u/2/folders/1APtRlvRBJguHWOQQO-u-wc0rPngeYcf2 

Should the status of this ticket be in "Preview" and then after going over in next week's sprint planning meeting, I close it?
